name = "PlutoSlides"
uuid = "ccaada3e-fbb3-407e-96e9-78c3ad6e4026"
authors = ["David MÃ©tivier <david.metivier@inrae.fr>"]
version = "0.1.0"

[deps]
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
HypertextLiteral = "0.9.5"
PlutoUI = "0.7.71"
Printf = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
